extends: "@ueno"
parser: babel-eslint
settings:
  import/resolver:
    webpack:
      config:
        resolve:
          extensions:
            - .js
            - .jsx
            - .json
          modules:
            - node_modules
            - ./
